name: Build & Publish Release JAR

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Make Gradle executable
      working-directory: ./api
      run: chmod +x ./gradlew
    - name: Build Release JAR
      working-directory: ./api
      run: ./gradlew assembleRelease
    - name: Releasing using Hub
      uses: kyze8439690/action-release-releaseapk@master
      env:
       APP_FOLDER: api
