name: Build an Run API

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Rodar WorkFlow Manualmente'     
        required: true
        default: 'warning'
      tags:
        description: 'Insira a TAG para o cenário'  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./api
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./api
        run: ./gradlew build --stacktrace
      - name: Try Run API on CI/CD Mode
        id: run
        working-directory: ./api
        run: ./gradlew bootRun -P prof=ci --stacktrace
