name: Build Api

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./api
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./api
        run: ./gradlew build --stacktrace
      - name: Run API
        working-directory: ./api
        run: ./gradlew bootRun --stacktrace
