name: Build Api

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres_db:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: api
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Make gradlew executable
        working-directory: ./api
        run: chmod +x ./gradlew
      - name: Build with Gradle
        working-directory: ./api
        run: ./gradlew build --stacktrace
      - name: Run API
        id: run
        working-directory: ./api
        run: ./gradlew bootRun --stacktrace
      - name: Check on failures
        if: steps.run.outputs.exit_status != 0 | steps.world.outputs.exit_status = 0
        run: exit 1
