name: Release
on:
  push:
    branches: [ main ]
    tags:
      - '*'
  
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Rodar WorkFlow Manualmente'     
        required: true
        default: 'warning'
      tags:
        description: 'Insira a TAG para o cenário'
env:
  VERSION_FILE: ./version.properties
  VERSION_EXTRACT_PATTERN: '(?<=VERSION=).+'

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: config git
      run: git config --global user.email "workflow@klocktecnologia.com" && git config --global user.name "WorkFlow Agent"

    - name: Generate version
      uses: HardNorth/github-version-generate@v1.1.1
      with:
        version-source: file
        version-file: ${{env.VERSION_FILE}}
        version-file-extraction-pattern: ${{env.VERSION_EXTRACT_PATTERN}}
    
    - name: Make Gradle executable
      working-directory: ./api
      run: chmod +x ./gradlew

    - name: Build Api Release with Gradle
      working-directory: ./api
      id: release
      run: |
        ./gradlew build -Prelease.useAutomaticVersion=true \
        -Prelease.releaseVersion=${{ env.RELEASE_VERSION }} \
        -Prelease.newVersion=${{ env.NEXT_VERSION }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Api do Docker Registry
      uses: docker/build-push-action@v2
      with:
        context: ./api
        build-args: |
          TAG=${{env.NEXT_VERSION}}
        push: true
        tags: "ejklock/api:${{env.NEXT_VERSION}}"
    
    - name: Build and push App do Docker Registry
      uses: docker/build-push-action@v2
      with:
        context: ./app
        build-args: |
          TAG=${{env.NEXT_VERSION}}
        push: true
        tags: "ejklock/app:${{env.NEXT_VERSION}}"
  
    - name: Create Release TAG
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_VERSION }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: ${{ steps.readChangelogEntry.outputs.log_entry }}
        draft: false
        prerelease: false
